# RabbitMQ连接配置
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    # 开启发布确认
    # NONE：禁用发布确认模式，为默认只
    # CORRELATED：发布消息成功到交换机后自动除非回调方法
    # SIMPLE：经测试有两种效果，其一效果和CORRELATED值一样会触发回调方法，
    # 其二在发布消息成功后使用rabbitTemplate调用waitForConfirms或 waitForConfirmsOrDie方法等待broker节点返回发送结果，根据返回结果来判定下一步的逻辑，要注意的点是
    # waitForConfirmsOrDie方法如果返回false则会关闭channel，则接下来无法发送消息到 broker
    # 相当于单个确认，未确认会阻塞等待
    publisher-confirm-type: correlated
    # 开启消息回退
    publisher-returns: true
